dataset: "cifar10"
num_classes: 2
data_dir: "./data/datasets"
device: "cuda"
seed: 43

data:
  samples_per_class: -1
  batch_size: 64
  num_workers: 1 # dataloader workers
  train_val_split: 0.8
  transforms:
    normalize: true # keep separate because it has to agree between train and test
    train:
      RandomHorizontalFlip:
        p: 0.5
      RandomRotation:
        degrees: 10
      RandomCrop:
        size: 32
        padding: 4
    test:
      RandomHorizontalFlip: null
      RandomRotation: null
      RandomCrop: null

model:
  architecture: "linear"
  config:
    hidden:
      - 512
      - 256

training:
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)

logging:
  wandb_logging: true
  wandb_project: "image-classification"
  wandb_entity: null
  log_freq: 10 # steps
  image_log_freq: 50 # steps
  watch_freq: 100 # steps
  checkpoint_freq: 100 # epochs
  checkpoint_root: "./data/checkpoints"
