defaults:
  - /../hydra@_here_
  - _self_

classifier_hydra_path: "classifiers/linear-cifar10/2024-12-27/20-41-01"
autoencoder_hydra_path: "autoencoders/convae-cifar10/2024-12-27/20-11-11"
name: "input_gradients"
seed: 100
device: "mps"

save_tensors: true
do_noae: true
do_ae: false

targets: null  # null or list[int]
fixed_target: 4

lr:
  no_ae: 0.001
  ae: 0.001
num_steps:
  no_ae: 300
  ae: 600
weight_decay: 0.0001
optimizer: AdamW
save_k_intermediate_imgs: 10
noise:
  perturb_weights: false
  stddev: 0.1

batch_size: 4
target_class: 9

dpi: 500
figsize: [30, 15]

# save outputs in classifier directory
hydra:
  run:
    dir: ${classifier_hydra_path}/input_gradients/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${classifier_hydra_path}/input_gradients/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}/seed=${seed}