classifier_hydra_path: "outputs/resnet9-fashion_mnist/2024-12-27/19-52-31"
autoencoder_hydra_path: "outputs/convae-fashion_mnist/2024-12-27/20-02-13"
name: "input_gradients"
seed: 100
device: "cuda"
do_noae: True
do_ae: True

lr:
  no_ae: 0.001
  ae: 0.001
num_steps:
  no_ae: 300
  ae: 1000
weight_decay: 0.0001
optimizer: AdamW
save_k_intermediate_imgs: 10

batch_size: 4
target_class: 9

dpi: 500
