defaults:
  - /../hydra@_here_
  - _self_

classifier_hydra_path: "classifiers/linear-cifar10/2024-12-27/20-41-01"
autoencoder_hydra_path: "autoencoders/convae-cifar10/2024-12-27/20-11-11"
name: "input_gradients"
seed: 100
device: "mps"

save_tensors: true
do_noae: True
do_ae: True

targets: null  # null or list[int]
fixed_target: 4

lr:
  no_ae: 0.001
  ae: 0.001
num_steps:
  no_ae: 300
  ae: 600
weight_decay: 0.0001
optimizer: AdamW
save_k_intermediate_imgs: 10

batch_size: 4
target_class: 9

dpi: 500
figsize: [30, 15]