hydra_path: "classifiers/resnet9-fashion_mnist"
name: "input_gradients"
seed: 42
device: "cuda"

lr: 0.001
weight_decay: 0.0001
num_steps: 3000
optimizer: AdamW
save_every_k: "auto"

batch_size: 4
target_class: 3