defaults:
  - /../hydra@_here_
  - base_training
  - _self_

name: "resnet18-vae-cifar10"
experiment_type: "train_vae_autoencoder"
description: "training a resnet18 variational autoencoder on cifar10"
device: "cuda"
seed: 100

model:
  type: "klae" #[klae, ae, <thats it for now>]
  architecture: "conv"
  config:
    block_type: "resnet"
    hidden_dims: [64, 128, 256, 512]
    downsample: [2, 2, 2, null]
    latent_dim: 512 # there is an additional convolution before going to z. maybe we should fix this
    z_channels: 24
    kl_weight: 0.1

training:
  save_model_artifact: true
  label_smoothing: 0.0
  epochs: 500
  weight_decay: 0.0001
  loss: "mse"
  reduce_lr:
    do: true
    mode: "min"
    monitor: "val/loss"
    factor: 0.1
    patience: 10

early_stopping:
  do: true
  monitor: "val/loss"
  mode: "min"
  patience: 50.0
