defaults:
  - data
  - logging
  - _self_

name: "prova"
seed: 43
device: "cuda"

model:
  architecture: "mlp"
  config:
    input_size: 784 # e.g., flattened 28x28 image
    hidden_dims: [512, 256] # dimensions for residual blocks
    latent_dim: 128 # bottleneck dimension
    block_kwargs:
      dropout: 0.1
      activation: "ReLU"

# model:
#   architecture: "conv"
#   config:
#     block_type: "convnext"
#     hidden_dims: [100, 50]
#     upsample: [2, 2]
#     downsample: [2, 2]

training:
  epochs: 1
  learning_rate: 0.001
  weight_decay: 0.0001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  loss: "mse"
