defaults:
  - /../hydra@_here_
  - base_training
  - _self_

name: "prova"
experiment_type: "train_autoencoder"
device: "cuda"
seed: 100

# model:
#   architecture: "mlp"
#   config:
#     hidden_dims: [512, 256] # dimensions for residual blocks
#     latent_dim: 128 # bottleneck dimension
#     block_kwargs:
#       dropout: 0.1
#       activation: "ReLU"

model:
  architecture: "conv"
  config:
    block_type: "convnext"
    hidden_dims: [128, 128]
    latent_dim: 32
    downsample: [2, 2]
    # block_kwargs:

training:
  loss: "mse"
