defaults:
  - data
  - logging
  - _self_

name: "prova"
seed: 43
device: "cuda"

# model:
#   architecture: "mlp"
#   config:
#     hidden_dims: [512, 256] # dimensions for residual blocks
#     latent_dim: 128 # bottleneck dimension
#     block_kwargs:
#       dropout: 0.1
#       activation: "ReLU"

model:
  architecture: "conv"
  config:
    block_type: "convnext"
    hidden_dims: [128, 256]
    latent_dim: 512
    downsample: [2, 2]
    # block_kwargs:

training:
  epochs: 1
  learning_rate: 0.001
  weight_decay: 0.0001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  loss: "mse"
