defaults:
  - /../data/base_data@_here_
  - /../logging/base_logging@_here_
  - _self_

name: ""
experiment_type: ???
device: "cuda"
seed: 100

training:
  epochs: 25
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  learning_rate: 0.0005
  gradient_clip_val: 1.0
  weight_decay: 0.0001
  adam_eps: 0.0000001
