defaults:
  - /../hydra@_here_
  - base_training
  - _self_

name: "prova"
experiment_type: "train_classifier"
device: "cuda"
seed: 100

dataset: "tiny_imagenet"

# model:
#   architecture: "mlp"
#   config:
#     hidden:
#       - 512
#       - 256

model:
  architecture: "resnet9"
  config:
    pretrained: true

training:
  label_smoothing: 0.05
