defaults:
  - data
  - logging
  - _self_

name: ""
seed: 43
device: "cuda"

model:
  architecture: "mlp"
  config:
    hidden:
      - 512
      - 256

training:
  epochs: 2
  learning_rate: 0.001
  weight_decay: 0.0001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  label_smoothing: 0.05
