defaults:
  - /../hydra@_here_
  - base_training
  - _self_

name: "prova"
experiment_type: "train_classifier"
device: "cuda"
seed: 100

dataset: "tiny_imagenet"

# model:
#   architecture: "mlp"
#   config:
#     hidden:
#       - 512
#       - 256

model:
  architecture: "resnet18"
  config:
    pretrained: false
    freeze_backbone: false

training:
  label_smoothing: 0.01
  epochs: 100
  weight_decay: 0.01

data:
  batch_size: 256
  transforms:
    train:
      RandomHorizontalFlip:
        p: 0.5
      RandomRotation:
        degrees: 10
      RandomCrop:
        size: 48
      ColorJitter:
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
