defaults:
  - data
  - logging
  - _self_

name: ""
device: "cuda"
seed: 100

# model:
#   architecture: "mlp"
#   config:
#     hidden:
#       - 512
#       - 256

model:
  architecture: "resnet9"
  config:
    pretrained: true

training:
  epochs: 50
  learning_rate: 0.001
  gradient_clip_val: 1.0
  weight_decay: 0.0001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  label_smoothing: 0.05
