logging:
  wandb_logging: true
  wandb_project: "autoencoders"
  wandb_entity: null
  log_freq: 10 # steps
  image_log_freq: 500 # steps
  watch_freq: 500 # steps
  checkpoint_freq: 100 # epochs
  save_last: False
  save_top_k: 1
  checkpoint_root: "./data/checkpoints"

hydra:
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - seed
          - name
  run:
    dir: outputs/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}/seed=${seed}
