logging:
  wandb_logging: true
  wandb_project: "image-classification"
  wandb_entity: null
  log_freq: 10 # steps
  image_log_freq: 50 # steps
  watch_freq: 100 # steps
  checkpoint_freq: 100 # epochs
  checkpoint_root: "./data/checkpoints"
