defaults:
  - data
  - training
  - logging
  - _self_

dataset: "fashion_mnist"
num_classes: 10
data_dir: "./data/datasets"
device: "cuda"
seed: 43

model:
  architecture: "mlp"
  config:
    hidden:
      - 512
      - 256
