hydra:
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - seed
          - name
  run:
    dir: outputs/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}/seed=${seed}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 4310
    cpus_per_task: 10
    mem_gb: 64
    nodes: 1
    name: ${hydra.job.name}
    partition: "long_gpu"
    gpus_per_task: 1
    array_parallelism: 1
    setup: 
      - conda activate genaug

