defaults:
  - /../training/base_training@_here_
  - data
  - logging
  - _self_

name: ""
experiment_type: "train_autoencoder_gda"
device: "cuda"
seed: 43

model:
  architecture: "conv"
  config:
    block_type: "convnext"
    hidden_dims: [128, 128]
    latent_dim: 32
    downsample: [2, 2]
    # block_kwargs:

logging:
  checkpoints:
    dirname: autoencoder_checkpoints
  image_log_freq: null

training:
  loss: "mse"