defaults:
  - logging
  - data
  - _self_

device: "cuda"
seed: 43
experiment_type: "train_autoencoder_gda"

model:
  architecture: "conv"
  config:
    block_type: "convnext"
    hidden_dims: [128, 128]
    latent_dim: 32
    downsample: [2, 2]
    # block_kwargs:

training:
  epochs: 25
  learning_rate: 0.001
  gradient_clip_val: 1.0
  weight_decay: 0.001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  loss: "mse"
  adam_eps: 0.0000001

logging:
  image_log_freq: null
  dirname: ""
