defaults:
  - logging
  - data
  - _self_

device: "cuda"
seed: 43

model:
  architecture: "conv"
  config:
    block_type: "convnext"
    hidden_dims: [128, 128]
    latent_dim: 32
    downsample: [1, 1]
    # block_kwargs:

training:
  epochs: 50
  learning_rate: 0.001
  gradient_clip_val: 1.0
  weight_decay: 0.0001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  loss: "mse"

logging:
  image_log_freq: null # hidden representations have too many channels
  dirname: ""
