defaults:
  - /../training/base_training@_here_
  - data
  - logging
  - _self_

name: ""
experiment_type: "pretrain_classifier_gda"
device: "cuda"
seed: 43

logging:
  checkpoints:
    dirname: classifier_checkpoints

model:
  architecture: "resnet9"
  config:
    pretrained: true

training:
  label_smoothing: 0.05