defaults:
  - logging
  - data
  - _self_

device: "cuda"
seed: 43

# model:
#   architecture: "linear"
#   config: null

model:
  architecture: "resnet9"
  config:
    pretrained: true  # ignored if unavailable

training:
  epochs: 25
  learning_rate: 0.001
  gradient_clip_val: 1.0
  weight_decay: 0.0001
  val_freq: 1.0 # fraction of epoch (float) or steps (int)
  label_smoothing: 0.05

logging:
  checkpoints:
    dirname: classifier_checkpoints
