defaults:
  - /../training/base_training@_here_
  - data
  - logging
  - _self_

name: "prova"
experiment_type: "finetune_classifier_gda"
device: "cuda"
seed: 43

layer_idx: null  # set at runtime
adversarial_augmentation:
  epsilon: 0.1

training:
  epochs: 20
  weight_decay: 0.001
  label_smoothing: 0.05

logging:
  checkpoints:
    dirname: finetuning_checkpoints
    save_last: false
