defaults:
  - autoencoder@autoencoder_config
  - classifier@classifier_config
  - finetuning@finetuning_config
  - _self_

name: "prova"

layers:
  - 0
  - 7
  - 17
  - 21

# for precomputing representations
hidden_representations_dataset:
  batch_size: 1024  
  num_workers: 8
  device: "cuda"

hydra:
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - seed
          - name
  run:
    dir: outputs/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}/seed=${seed}

wandb_logging: ${logging.logging.wandb_logging}