defaults:
  - /../hydra@_here_
  - autoencoder@autoencoder_config
  - classifier@classifier_config
  - finetuning@finetuning_config
  - _self_

name: "prova"
experiment_type: "gda"
layers:
  - 0
  - 7
  - 17
  - 21

# for precomputing internal representations
hidden_representations_dataset:
  precomputing:
    batch_size: 1024  
    num_workers: 8
    device: "cuda"
  batch_size: ${data.data.batch_size}
  num_workers: ${data.data.num_workers}

wandb_logging: ${logging.logging.wandb_logging}