logging:
  wandb_logging: true
  wandb_project: "generative-data-augmentation"
  wandb_entity: "mattia-scardecchia"
  log_freq: 10 # steps
  image_log_freq: 500 # steps
  watch_freq: 500 # steps
  checkpoints:
    checkpoint_freq: 5 # epochs
    save_last: True
    save_top_k: 0
    monitor: "val/loss"
    mode: "min"
    dirname: "checkpoints"
