logging:
  wandb_logging: true
  wandb_project: "Generative-Data-Augmentation"
  wandb_entity: "willinki-bocconi-university"
  log_freq: 10 # steps
  image_log_freq: 500 # steps
  watch_freq: 500 # steps
  checkpoints:
    checkpoint_freq: 5 # epochs
    save_last: True
    save_top_k: 1
    monitor: "val/loss"
    mode: "min"
    dirname: "checkpoints"
